name: opensearch

services:
  opensearch:
    image: opensearchproject/opensearch:${STACK_VERSION}
    container_name: opensearch
    hostname: opensearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - data:/usr/share/opensearch/data
    ports:
      - ${OPENSEARCH_PORT}:9200
      - ${OPENSEARCH_PA_PORT}:9600

  dashboards:
    image: opensearchproject/opensearch-dashboards:${STACK_VERSION}
    container_name: opensearch-dashboards
    depends_on:
      - opensearch
    ports:
      - ${DASHBOARDS_PORT}:5601
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'

volumes:
  data:
    name: vol-opensearch

networks:
  default:
    name: nw-opensearch
