version: '3'

services:
  neo4j:
    image: neo4j:${NEO4J_VERSION}
    container_name: neo4j
    ports:
      - "${NEO4J_HTTP_PORT}:7474"  # HTTP
      - "${NEO4J_BOLT_PORT}:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
      - NEO4J_dbms_memory_pagecache_size=${NEO4J_PAGECACHE_SIZE}
      - NEO4J_dbms_memory_heap_initial__size=${NEO4J_HEAP_INITIAL_SIZE}
      - NEO4J_dbms_memory_heap_max__size=${NEO4J_HEAP_MAX_SIZE}
    volumes:
      - ${NEO4J_DATA}:/data
      - ${NEO4J_LOGS}:/logs
      - ${NEO4J_CONF}:/conf
      - ${NEO4J_PLUGINS}:/plugins
    restart: unless-stopped

networks:
  default:
    name: nw-neo4j