name: zookeeper

services:
  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.9
    hostname: zookeeper
    ports:
      - ${ZK1_PORT}:2181
    volumes:
      - data:/data
      - datalog:/datalog
      - logs:/logs

volumes:
  data:
    name: vol-zk-data
  datalog:
    name: vol-zk-datalog
  logs:
    name: vol-zk-logs

networks:
  default:
    name: nw-zk
