version: "1.1"

services:
  ng:
    image: nginx:1
    container_name: nginx
    volumes:
    - ${VOL_NG_CONF_FILE}:/etc/nginx/nginx.conf
    - ${VOL_NG_CONF_D}:/etc/nginx/conf.d
    ports:
    - 80:80

networks:
  default:
    name: nw-ng
