version: "1.1"

services:
  ng:
    image: nginx:1
    container_name: nginx
    restart: always
    volumes:
    - ./conf/nginx.conf:/etc/nginx/nginx.conf
    - ./conf/conf.d:/etc/nginx/conf.d
    ports:
    - 80:80

networks:
  default:
    name: nw-ng
