version: "1.1"

services:
  ng:
    image: nginx:1
    restart: always
    volumes:
    - ~/code/docker/ng/nginx.conf:/etc/nginx/nginx.conf
    - ~/code/docker/ng/conf.d:/etc/nginx/conf.d
    ports:
    - 80:80

networks:
  default:
    name: nw-ng
