name: mysql

services:
  mysql:
    container_name: mysql
    hostname: mysql
    image: mysql:8
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ${MYSQL_DATA}:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
      - ${MYSQLX_PORT}:33060
networks:
  default:
    name: nw-mysql
