version: "1.0"

services:
  jm:
    container_name: flink-jm
    image: flink:1.18
    ports:
      - ${FLINK_JOBMANAGER_PORT}:8081
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jm

  tm:
    image: flink:1.18
    depends_on:
      - jm
    command: taskmanager
    scale: 4
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jm
        taskmanager.numberOfTaskSlots: 2

  sc:
    container_name: flink-sc
    image: flink:1.18
    command: bin/sql-client.sh
    depends_on:
      - jm
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jm
        rest.address: flink-jm

networks:
  default:
    name: nw-flink
