version: "1.0"

# not ready
services:
  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    volumes:
      - secrets:/etc/kafka/secrets
      - config:/mnt/shared/config
      - data:/var/lib/kafka/data
    ports:
      - ${KAFKA_PORT}:9092

volumes:
  secrets:
    name: vol-kafka-secrets
  config:
    name: vol-kafka-config
  data:
    name: vol-kafka-data

networks:
  default:
    name: nw-zk
    external: true
