version: "1.0"

# not ready
services:
  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    restart: always
    external_links:
      - zk-1:zookeeper
    volumes:
      - secrets:/etc/kafka/secrets
      - config:/mnt/shared/config
      - data:/var/lib/kafka/data
    networks:
      - default
      - nw-all
    ports:
      - ${KAFKA_PORT}:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181

volumes:
  secrets:
    name: vol-kafka-secrets
  config:
    name: vol-kafka-config
  data:
    name: vol-kafka-data

networks:
  default:
    name: nw-all
    external: true
  nw-zk:
    name: nw-zk
    external: true
