version: "1.0"

services:
  kafka:
    image: ubuntu/kafka:3.1-22.04_edge
    container_name: kafka
    ports:
      - ${KAFKA_PORT}:9092
    environment:
      - TZ=GMT+8
      - ZOOKEEPER_HOST=zookeeper
    external_links:
      - zookeeper:zookeeper

networks:
  default:
    name: nw-zk
    external: true
