name: postgres

services:
  pg:
    image: ${BASE_IMAGE}
    # image: pgzh
    # build:
    #   context: .
    #   dockerfile_inline: |
    #     FROM ${BASE_IMAGE}
    #     RUN localedef -i zh_CN -c -f UTF-8 -A /usr/share/locale/locale.alias zh_CN.UTF-8
    #     ENV LANG zh_CN.utf8
    #   cache_from:
    #     - ${BASE_IMAGE}
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ${POSTGRES_DATA}:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432

networks:
  default:
    name: nw-postgres
