version: "1.1"

services:
  c-pg16:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - nw-all

volumes:
  pgdata:
    name: vol-pg16
    driver: local

networks:
  nw-all:
    name: nw-all
    external: true