version: "1.0"

services:
  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - data:/data

volumes:
  data:
    name: vol-redis

networks:
  default:
    name: nw-redis
