version: "1.0"

services:
  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - data:/data
    networks:
      - nw-all

volumes:
  data:
    name: vol-redis
    driver: local

networks:
  nw-all:
    name: nw-all
    external: true
