name: redis

services:
  redis:
    image: redis:7
    container_name: redis
    command: ['redis-server', '--requirepass', '${REDIS_PORT}']
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - data:/data

volumes:
  data:
    name: vol-redis

networks:
  default:
    name: nw-redis
